
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-deployment
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: santa
  template:
    metadata: 
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: rajesh947/secret-santa # Replace with the actual image tag
          ports:
            - containerPort: 8080 # Replace with the port your Tetris game listens on

